### ISSUE TITLE
An error about demo2

### ISSUE THREAD

**Issue by LYX-ll** [robotic-vision-lab/Dual-Interactive-Implicit-Neural-Network#9]
Hi, very excellent work. 
I want to test your checkpoint, but I get an error when running demo2:

(base) root@395941981081047040-taskrole1-0:/gemini/code/Dual-Interactive-Implicit-Neural-Network-update# python demo2.py --lr_path=./lr/0901x3.png --ckpt_path=./ckpt/diinn_pretrained.ckpt --output_size 3 3
Lightning automatically upgraded your loaded checkpoint from v1.6.4 to v2.1.2. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint ckpt/diinn_pretrained.ckpt`
./lr/0901x3.png
./ckpt/diinn_pretrained.ckpt
Traceback (most recent call last):
  File "/gemini/code/Dual-Interactive-Implicit-Neural-Network-update/demo2.py", line 46, in <module>
    demo2(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/gemini/code/Dual-Interactive-Implicit-Neural-Network-update/demo2.py", line 42, in demo2
    sr = model(lr, args.output_size)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gemini/code/Dual-Interactive-Implicit-Neural-Network-update/src/models/sr_module.py", line 105, in forward
    return self.net(x, size, eval_bsize)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gemini/code/Dual-Interactive-Implicit-Neural-Network-update/src/models/components/diinn.py", line 17, in forward
    x = self.encoder(x)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/gemini/code/Dual-Interactive-Implicit-Neural-Network-update/src/models/components/rdn.py", line 91, in forward
    f__1 = self.SFENet1(x)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same or input should be a MKLDNN tensor and weight is a dense tensor

**Comment by hquan7395** [comment]
Hi,

Thank you for your interest in our work and apologies for the late response. The Error seems to complain that the input (LR image) and the model parameters are not on the same device. Could you please try again with this change:
https://github.com/robotic-vision-lab/Dual-Interactive-Implicit-Neural-Network/blob/6775b4624ec1f6f8cc9e5ca3d44e7ef5685af7ca/demo2.py#L40

sr = model(lr.cuda() , args.output_size)

I didn't have this error when I tested the demo a while ago but maybe this happens because of the newer versions of the dependencies.

**Comment by LYX-ll** [comment]
Thank you, I appreciate your patience.
